## @file
#

SUB_DEPTH = .
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/netx/Makefile.kmk
include $(PATH_SUB_CURRENT)/plugin/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)
